'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''


# 1 Hash
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        compare = {}
        for i in s:
            if compare.__contains__(i): compare[i] += 1
            else: compare[i] = 1
        for j in t:
            if compare.__contains__(j):
                compare[j] -= 1
                if compare[j] == 0: del compare[j]
            else: return j
        return compare.keys()[0]


# 2 Collections
from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return list((Counter(t) - Counter(s)).keys())[0]